version: '3.8'

services:
  server:
    build:
      context: ./smosky-boilerplate-server
      dockerfile: Dockerfile
    container_name: smosky-boilerplate-server
    ports:
      - "8090:8090"
    volumes:
      - ./smosky-boilerplate-server/zip:/app/zip
      - ./smosky-boilerplate-server/zip-response:/app/zip-response
      - ./smosky-boilerplate-server/extract-zip:/app/extract-zip
    networks:
      - blog-network
    restart: unless-stopped

  app:
    build:
      context: ./smosky-client
      dockerfile: Dockerfile
    container_name: smosky-app
    env_file:
      - ./smosky-client/.env
    ports:
      - "8000:8000"
    networks:
      - blog-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  blog-network:
    external: true
    name: blogging_blog-network